# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - TV
  - Podcasts
  - News
  - 'App Store'
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "PhpStorm"
    path: "/Applications/PhpStorm.app/"
    pos: 4
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 5
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6
  - name: "Tower"
    path: "/Applications/Tower.app/"
    pos: 7
  - name: "Mimestream"
    path: "/Applications/Mimestream.app/"
    pos: 8
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 9

dotfiles_repo: https://github.com/suth/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Code/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .p10k.zsh

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - composer
  # - gifsicle
  - git
  # - httpie
  - iperf
  - mkcert
  # - nmap
  - node
  - nss
  - nvm
  - php
  - ssh-copy-id
  # - openssl
  - wget
  # - wrk
  - yt-dlp
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - romkatv/powerlevel10k/powerlevel10k

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_apps:
  - 1password
  # - adobe-creative-cloud
  # - alfred
  # - autodesk-fusion360
  - balenaetcher
  - bettertouchtool
  - brave-browser
  - dash
  - discord
  - docker
  - firefox
  - font-fira-code
  - font-fira-code-nerd-font
  - google-chrome
  - iina
  - iterm2
  - licecap
  - maestral
  - mimestream
  - minecraft
  - phpstorm
  - postman
  - prusaslicer
  - raspberry-pi-imager
  - raycast
  - slack
  - sublime-text
  - tableplus
  - tower
  - visual-studio-code
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1569813296, name: "1Password for Safari" }
  # - { id: 497799835, name: "Xcode" }
  # - { id: 409183694, name: "Keynote" }
  # - { id: 408981434, name: "iMovie" }
  - { id: 1099568401, name: "Home Assistant" }
  - { id: 1573461917, name: "SponsorBlock for YouTube" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 1463298887, name: "Userscripts" }
  - { id: 290986013, name: "Deliveries" }
  - { id: 1480933944, name: "Vimari" }
  # - { id: 409201541, name: "Pages" }
  - { id: 425264550, name: "Disk Speed Test" }
  - { id: 1544743900, name: "Hush" }
  # - { id: 682658836, name: "GarageBand" }
  - { id: 1570922521, name: "Sauce for Strava" }
  # - { id: 409203825, name: "Numbers" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 1524828965, name: "Tweaks for Reddit" }

osx_script: "~/.osx --no-restart"

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_package_control:
  - "Theme - One Dark"
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"
