# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - TV
  - Podcasts
  - News
  - 'App Store'
dockitems_persist:
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 3
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 4
  - name: "PhpStorm"
    path: "/Applications/PhpStorm.app/"
    pos: 5
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 6
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 7
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 8

dotfiles_repo: https://github.com/suth/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .p10k.zsh

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  # - gifsicle
  - git
  # - httpie
  - iperf
  # - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  # - openssl
  - wget
  # - wrk
  - zsh-history-substring-search
  - romkatv/powerlevel10k/powerlevel10k

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_apps:
  - docker
  - dropbox
  - google-chrome
  - brave-browser
  - firefox
  - alfred
  - licecap
  - tableplus
  - slack
  - discord
  - vlc
  - bettertouchtool
  - iterm2
  - phpstorm
  - postman
  - sublime-text
  - fork
  - dash
  - autodesk-fusion360
  - prusaslicer
  - raspberry-pi-imager
  - balenaetcher
  - minecraft
  - font-fira-code
  - font-fira-code-nerd-font

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 425264550, name: "Blackmagic Disk Speed Test" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1099568401, name: "Home Assistant" }

osx_script: "~/.osx --no-restart"

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_package_control:
  - "Theme - One Dark"
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"
